services:
  postgres-test:
    image: postgres:17
    container_name: postgres-test
    shm_size: 128mb
    environment:
      POSTGRES_USER: app-test
      POSTGRES_PASSWORD: app-test
      POSTGRES_DB: app-test
    ports:
      - "5433:5432"
