services:
  postgres:
    image: postgres:17
    container_name: postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d app" ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - postgres-empikdc-data:/var/lib/postgresql/data

  empikdc:
    build: .
    container_name: empikdc
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/app
      DATASOURCE_USERNAME: app
      DATASOURCE_PASSWORD: app
    depends_on:
      - postgres

volumes:
  postgres-empikdc-data: