spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/app-test
    username: app-test
    password: app-test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

management:
  prometheus:
    enabled: false

app:
  cache:
    enabled: false
